name: Build and test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v5
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build tropic01
      run: |
        cargo build --package tropic01 --no-default-features
        cargo build --package tropic01
        cargo build --package tropic01 --all-features
    - name: Build tropic01-example-rpi
      run: |
        cargo build --package tropic01-example-rpi
    - name: Run tests
      run: cargo test

  build-no-std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    env:
      CARGO_BUILD_TARGET: thumbv8m.main-none-eabi
    steps:
    - uses: actions/checkout@v5
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Install ${{ env.CARGO_BUILD_TARGET }} target
      run: rustup target add ${CARGO_BUILD_TARGET}
    - name: Build tropic01
      run: |
        cargo build --package tropic01 --no-default-features
        cargo build --package tropic01
        cargo build --package tropic01 --all-features
