name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
    - name: Build tropic01
      run: |
        cargo build --package tropic01 --no-default-features
        cargo build --package tropic01
        cargo build --package tropic01 --all-features
    - name: Build tropic01-example-rpi
      run: |
        cargo build --package tropic01-example-rpi
    - name: Check formatting
      run: cargo fmt --all --check
    - name: Check clippy lints
      run: cargo clippy --workspace --all-features --all-targets -- --deny warnings
    - name: Run tests
      run: cargo test

  build-no-std:
    runs-on: ubuntu-latest
    env:
      CARGO_BUILD_TARGET: thumbv8m.main-none-eabi
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
    - name: Install ${{ env.CARGO_BUILD_TARGET }} target
      run: rustup target add ${CARGO_BUILD_TARGET}
    - name: Build tropic01
      run: |
        cargo build --package tropic01 --no-default-features
        cargo build --package tropic01
        cargo build --package tropic01 --all-features
